import { StyleSheet } from "react-native";
import { theme } from "@/styles/theme";

/** Home / 快捷记录：工业高能效深色主题，列表项 surface + 12px 圆角。 */
export const styles = StyleSheet.create({
  container: {
    flex: 1,
    minHeight: "100%",
    justifyContent: "center",
    alignItems: "center",
    padding: theme.spacing.l,
    backgroundColor: theme.colors.background,
  },
  section: {
    width: "100%",
    maxWidth: 400,
    alignItems: "stretch",
  },
  scrollSection: {
    width: "100%",
    maxWidth: 400,
  },
  scrollContent: {
    alignItems: "stretch",
    paddingBottom: theme.spacing.l,
  },
  sectionTitle: {
    ...theme.typography.title,
    color: theme.colors.textPrimary,
    textAlign: "center",
    marginBottom: theme.spacing.m,
  },
  input: {
    borderWidth: 1,
    borderColor: theme.colors.border,
    borderRadius: theme.borderRadius.m,
    padding: theme.spacing.m,
    ...theme.typography.body,
    minHeight: theme.layout.touchableHeight,
    marginBottom: theme.spacing.m,
    backgroundColor: theme.colors.surface,
    color: theme.colors.textPrimary,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 2,
  },
  button: {
    minHeight: theme.layout.touchableHeight,
    backgroundColor: theme.colors.primary,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: theme.borderRadius.m,
    marginBottom: theme.spacing.l,
  },
  buttonPressed: { opacity: 0.8 },
  buttonDisabled: { opacity: 0.6 },
  buttonText: {
    color: theme.colors.textOnDark,
    ...theme.typography.body,
    fontWeight: "600",
  },
  linkBox: {
    width: "100%",
    padding: theme.spacing.m,
    backgroundColor: theme.colors.surface,
    borderRadius: theme.borderRadius.m,
    marginBottom: theme.spacing.m,
    borderWidth: 1,
    borderColor: theme.colors.border,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 2,
  },
  linkText: {
    ...theme.typography.caption,
    color: theme.colors.textSecondary,
    flexShrink: 1,
  },
  copyButton: {
    minHeight: theme.layout.touchableHeight,
    backgroundColor: theme.colors.success,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: theme.borderRadius.m,
  },
  copyButtonPressed: { opacity: 0.8 },
  copyButtonText: {
    color: theme.colors.textOnDark,
    ...theme.typography.body,
    fontWeight: "600",
  },
  listTitle: {
    ...theme.typography.title,
    color: theme.colors.textPrimary,
    textAlign: "center",
    marginTop: theme.spacing.l,
    marginBottom: theme.spacing.m,
  },
  list: {
    width: "100%",
    flexGrow: 0,
  },
  listItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    minHeight: 72,
    maxHeight: 80,
    paddingVertical: theme.spacing.m,
    paddingHorizontal: theme.spacing.m,
    marginBottom: theme.spacing.s,
    backgroundColor: theme.colors.surface,
    borderRadius: theme.borderRadius.l,
    borderWidth: 1,
    borderColor: theme.colors.border,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 2,
  },
  listItemLeft: {
    flex: 1,
    marginRight: theme.spacing.m,
    justifyContent: "center",
  },
  listItemName: {
    ...theme.typography.body,
    fontWeight: "600",
    color: theme.colors.textPrimary,
    marginBottom: theme.spacing.xs,
  },
  listItemStatus: {
    ...theme.typography.caption,
    color: theme.colors.textSecondary,
  },
  listItemActions: {
    flexDirection: "row",
    alignItems: "center",
  },
  listItemCopyButton: {
    minHeight: theme.layout.touchableHeight,
    minWidth: theme.layout.touchableHeight,
    backgroundColor: theme.colors.success,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: theme.borderRadius.m,
  },
  listItemCopyButtonPressed: { opacity: 0.8 },
  listItemCopyButtonMargin: { marginRight: theme.spacing.s },
  listItemRevokeButton: {
    minHeight: theme.layout.touchableHeight,
    minWidth: theme.layout.touchableHeight,
    backgroundColor: theme.colors.danger,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: theme.borderRadius.m,
  },
  listItemRevokeButtonPressed: { opacity: 0.8 },
  listItemButtonText: {
    color: theme.colors.textOnDark,
    ...theme.typography.caption,
  },
});
